### ISSUE TITLE
Unable to find acceptable protocols with okhttp3:okhttp:3.13.1

### ISSUE THREAD

**Issue by tranducthang1505** [dropbox/dropbox-sdk-java#246]
Hi. I just update okhttp version to 3.14.1. After, I run the app and  encountered a problem
when I I tried to get the data or logout (login is okay)
This is not a serious error if I downgrade the okhttp version, but I hope you will fix it soon

NetworkIOException error:
`Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_3, TLS_1_2], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1]`

**Comment by greg-db** [comment]
Thanks for the report! I can't seem to reproduce this particular error though. Can you share the code necessary to reproduce this? Thanks in advance!

**Comment by cakoose** [comment]
Getting the steps/code to reproduce would definitely be useful.

But until then, here are some rough guesses based on the code.  This is what the OkHttp code that throws the exception looks like:

```
    if (tlsConfiguration == null) {
      // This may be the first time a connection has been attempted and the socket does not support
      // any the required protocols, or it may be a retry (but this socket supports fewer
      // protocols than was suggested by a prior socket).
      throw new UnknownServiceException(
          "Unable to find acceptable protocols. isFallback=" + isFallback
              + ", modes=" + connectionSpecs
              + ", supported protocols=" + Arrays.toString(sslSocket.getEnabledProtocols()));
    }
```

Basically, `sslSocket.getEnabledProtocols()` only has "TLSv1" in it, which is somehow incompatible with the `tlsVersions` array, whatever that is.

The Dropbox Java SDK currently has an bug where it calls `setEnabledProtocols(...)` with just TLSv1 ([code](https://github.com/dropbox/dropbox-sdk-java/blob/5efacbdb4531b4c247cde130131d9bac08192135/src/main/java/com/dropbox/core/http/SSLConfig.java#L168)).

This bug hasn't caused things to fail so far, probably because using TLSv1 was ok.  As more libraries and platforms start disallowing TLSv1, this bug will probably start causing things to fail.

There is a fix for this particular bug: #241.

**Comment by adityabhaskar** [comment]
I'm getting the same error after updating okhttp3. 
_Do we know the latest version of okhttp with which the SDK works?_

Using:
SDK ver 3.0.11
okhttp3 ver 3.14.1

Code:
```
        try {
            return mDbxClient.users().currentAccount
        } catch (e: DbxException) {
            mException = e
        }
```

Error: 
```
com.dropbox.core.NetworkIOException: Unable to find acceptable protocols. 
isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, 
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, 
TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, 
TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], 
tlsVersions=[TLS_1_3, TLS_1_2], supportsTlsExtensions=true), ConnectionSpec()], 
supported protocols=[TLSv1]
```

**Comment by greg-db** [comment]
@adityabhaskar Thanks for the information! I'm glad to hear you were already able to work around this.

**Comment by drakeet** [comment]
Getting the same error when using okhttp `4.2.1`.
![image](https://user-images.githubusercontent.com/5214214/67617275-1234df00-f814-11e9-92ef-f04416de0691.png)
FYI, my app `minSdkVersion` is 21.

**Comment by greg-db** [comment]
Apologies for the lack of updates on this issue. I believe [v3.1.1](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.1.1) should have fixed this. @drakeet (and others on this thread if you haven't already), can you update to [v3.1.1](https://github.com/dropbox/dropbox-sdk-java/releases/tag/v3.1.1) and let me know if that does or doesn't help? Thanks!

**Comment by kungufli** [comment]
@greg-db Thanks, I can confirm that the issue is fixed. Tested on SDK 3.1.1 and okhttp3 4.0.0

**Comment by skathar** [comment]
I am using okhttp3 (okhttp-3.9.0.jar) still getting same error, can you please help me with this.

java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(tlsVersions=[TLS_1_2], supportsTlsExtensions=true)], supported protocols=[TLSv1]
okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:73)

**Comment by greg-db** [comment]
@skathar This issue should have been resolved as of v3.1.1 of the Dropbox Java SDK. Can you let me know what version you're using? That latest release is v3.1.3, so please update to that and try again if you're not already using it.

**Comment by skathar** [comment]
@greg-db Thank you for your response, but is it fixed in Dropbox SDK or okHttp jar. I am using okhttp-4.5.0.jar, still getting this exception.

**Comment by greg-db** [comment]
@skathar This was fixed via https://github.com/dropbox/dropbox-sdk-java/commit/68ccc02c99a34f77b02e821d3d004186205a7363 in the Dropbox Java SDK, not the OkHttp library. If you're using the Dropbox Java SDK and are still having trouble with this, please share:
- the version number of the Dropbox Java SDK you're using
- the steps and code to reproduce the issue

Please note that if you're referring to using OkHttp itself, and not the Dropbox Java SDK, we can't offer help with that as it's not made by Dropbox.

**Comment by chaithugrandhe** [comment]
Hi 

Am facing the below issue, can anyone help me to solve it. Thanks 

run: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_DHE_RSA_WITH_AES_256_CBC_SHA256], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)], supported protocols=[SSLv3, TLSv1, TLSv1.1, TLSv1.2]

**Comment by greg-db** [comment]
@chaithugrandhe This issue should have been resolved as of v3.1.1 of the Dropbox Java SDK. Can you let me know what version you're using? That latest release is v4.0.0, so please update to that and try again if you're not already using it.

**Comment by chaithugrandhe** [comment]
Hi @greg-db,
I don't have Dropbox Java SDK in my project, am using android studio, in order to resolve the issue should I need to include it in my project?

**Comment by chaithugrandhe** [comment]
Hi @greg-db 

after adding implementation 'com.dropbox.core:dropbox-core-sdk:4.0.0' still the error remains same, what could be the reason?

**Comment by greg-db** [comment]
@chaithugrandhe This issue was referring to using this Dropbox Java SDK. It sounds like you are not actually using the SDK though. We do recommend using it when integrating with the Dropbox API in Java/on Android though. You would use the Dropbox Java SDK methods instead of using your own HTTPS client to call the Dropbox API endpoints yourself. 

If you wish to do so, please refer to the instructions here for getting set up with the Dropbox Java SDK: 

https://github.com/dropbox/dropbox-sdk-java#dropbox-core-sdk-for-java-8

There's an Android example here:

https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android

If you do run in to any issues with the Dropbox Java SDK itself, please [open a new issue](https://github.com/dropbox/dropbox-sdk-java/issues/new) with the details of the issue so we can take a look.
